src/Entity/Characters.php
<?php

namespace App\Entity;

use App\Repository\CharactersRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: CharactersRepository::class)]
class Characters
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $Nombre = null;

    #[ORM\Column(length: 250, nullable: true)]
    private ?string $Pelicula = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $Tipo = null;

    #[ORM\Column(length: 150, nullable: true)]
    private ?string $Localizacion = null;

    #[ORM\Column(length: 255)]
    private ?string $Imagen = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNombre(): ?string
    {
        return $this->Nombre;
    }

    public function setNombre(string $Nombre): self
    {
        $this->Nombre = $Nombre;

        return $this;
    }

    public function getPelicula(): ?string
    {
        return $this->Pelicula;
    }

    public function setPelicula(string $Pelicula): self
    {
        $this->Pelicula= $Pelicula;

        return $this;
    }

    public function getTipo(): ?string
    {
        return $this->Tipo;
    }

    public function setTipo(?string $Tipo): self
    {
        $this->Tipo = $Tipo;

        return $this;
    }

    public function getLocalizacion(): ?string
    {
        return $this->Localizacion;
    }

    public function setLocalizacion(?string $Localizacion): self
    {
        $this->Localizacion = $Localizacion;

        return $this;
    }

    public function getImagen(): ?string
    {
        return $this->Imagen;
    }

    public function setImagen(string $Imagen): self
    {
        $this->Imagen = $Imagen;

        return $this;
    }
}

src/Form/NewCharacterType.php
<?php

namespace App\Form;

use App\Entity\Characters;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class NewCharacterType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nombre', TextType::class,
            ['attr' => ['placeholder' => 'Ej. Hades']])
            ->add('Pelicula', TextType::class, ["label"=>"Película", 'attr' => ['placeholder' => 'Ej. Hércules']])
            ->add('Tipo', TextType::class,
            ['attr' => ['placeholder' => 'Ej. Villano']])
            ->add('Localizacion', TextType::class, ["label"=>"Localización", 'attr' => ['placeholder' => 'Ej. Inframundo']])
            ->add('Imagen', TextType::class,
            ['attr' => ['placeholder' => 'Introduce una URL']])
            ->add('Enviar', SubmitType::class)
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Characters::class,
        ]);
    }
}

src/Controller/DisneyController.php
<?php

namespace App\Controller;

use App\Entity\Characters;
use App\Form\NewCharacterType;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DisneyController extends AbstractController {

    #[Route('/charactersList', name:"charactersList")]
    public function getCharactersList(EntityManagerInterface $doctrine, Request $request){
        $repositorio=$doctrine->getRepository(Characters::class);
        $characters=$repositorio->findAll();
        return $this -> render("characters/charactersList.html.twig", ["characters" => $characters]);
    }

    #[Route('/characterDetail/{id}', name:"characterDetail")]
    public function getCharacterDetail(EntityManagerInterface $doctrine, $id){
        $repositorio=$doctrine->getRepository(Characters::class);
        $character=$repositorio->find($id);
        return $this -> render("characters/characterDetail.html.twig", ['character'=> $character]);
    }

    #[Route('/new/character', name:"newCharacters")]
    public function createCharacters(EntityManagerInterface $doctrine){
        $character1= new Characters();
       $character1->setNombre("Cenicienta");
       $character1->setTipo("Princesa");
       $character1->setPelicula ("La Cenicienta");
       $character1->setImagen("https://a-desk.org/wp-content/uploads/2015/11/cenicienta-limpiando__a-desk-595x400.jpg");
       $character1->setLocalizacion("Alemania");

       $character2= new Characters();
       $character2->setNombre("Hércules");
       $character2->setTipo("Héroe");
       $character2->setPelicula("Hércules");
       $character2->setImagen("https://img2.freepng.es/20190126/qwt/kisspng-heracles-hercules-clip-art-openclipart-image-hercules-5c4d1b59377938.7330523015485571452272.jpg");
       $character2->setLocalizacion("Grecia");

       $character3= new Characters();
       $character3->setNombre("Mike Wazowski");
       $character3->setTipo("Monstruo");
       $character3->setPelicula("Monstruos S.A.");
       $character3->setImagen("https://img.fruugo.com/product/8/43/7700438_max.jpg");
       $character3->setLocalizacion("Monstruópolis");

       $character4= new Characters();
       $character4->setNombre("Stich");
       $character4->setTipo("Extraterrestre");
       $character4->setPelicula("Lilo & Stich");
       $character4->setImagen("https://upload.wikimedia.org/wikipedia/en/thumb/d/d2/Stitch_%28Lilo_%26_Stitch%29.svg/640px-Stitch_%28Lilo_%26_Stitch%29.svg.png");
       $character4->setLocalizacion("Hawai");

       $character5= new Characters();
       $character5->setNombre("Woody");
       $character5->setTipo("Juguete");
       $character5->setPelicula("Toy Story");
       $character5->setImagen("https://media.vandalsports.com/i/1706x960/7-2022/202277162619_1.jpg.webp");
       $character5->setLocalizacion("Estados Unidos");

       $character6= new Characters();
       $character6->setNombre("Jafar");
       $character6->setTipo("Villano");
       $character6->setPelicula("Aladdin");
       $character6->setImagen("https://hips.hearstapps.com/es.h-cdn.co/fotoes/images/peliculas-para-ninos-cine-infantil/personajes-disney-orgullo-lgtbi/jafar-aladdin/138118167-1-esl-ES/Jafar-Aladdin.jpg");
       $character6->setLocalizacion("Arabia");

       $character7= new Characters();
       $character7->setNombre("Úrsula");
       $character7->setTipo("Villana");
       $character7->setPelicula("La Sirenita");
       $character7->setImagen("https://eltallerdehector.com/wp-content/uploads/2022/06/943eb-personajes-de-la-sirenita-png-ursula.png");
       $character7->setLocalizacion("Atlántida");

       $doctrine->persist($character1);
       $doctrine->persist($character2);
       $doctrine->persist($character3);
       $doctrine->persist($character4);
       $doctrine->persist($character5);
       $doctrine->persist($character6);
       $doctrine->persist($character7);

       $doctrine->flush();
       return new Response("Personajes insertados correctamente");
    }

    #[Route('/insert/character', name:"insertCharacter")]
    public function insertCharacter(Request $request ,EntityManagerInterface $doctrine){

        $form = $this -> createForm(NewCharacterType::class);

        $form-> handleRequest($request);

        if($form -> isSubmitted()&& $form -> isValid()){
            $character = $form -> getData();
            $doctrine -> persist($character);
            $doctrine -> flush();
        }

        return $this-> renderForm("/characters/createCharacter.html.twig", ["createForm"=>$form]);

        $this->addFlash('success', 'Personaje creado correctamente');
    }

    #[Route('/delete/character/{id}', name:'deleteCharacter')]
    public function deleteCharacter(EntityManagerInterface $doctrine, $id){
        $repositorio=$doctrine->getRepository(Characters::class);
        $character=$repositorio->find($id);
        $doctrine->remove($character);
        $doctrine->flush();
        $this->addFlash('success', 'Personaje borrado correctamente');
        return $this-> redirectToRoute('charactersList');
    }
}

templates/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block title %}Welcome!{% endblock %}</title>
        <link rel="icon" href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 128 128%22><text y=%221.2em%22 font-size=%2296%22>⚫️</text></svg>">
        {# Run `composer require symfony/webpack-encore-bundle` to start using Symfony UX #}
        {% block stylesheets %}
            {{ encore_entry_link_tags('app') }}
        {% endblock %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
    </head>
    <body>
        {% block body %}{% endblock %}
    </body>
</html>

templates/characters/baseDisney.html.twig
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <title>{% block title %}Disney Characters{% endblock %}</title>
    {% block stylesheets %}
      {{ encore_entry_link_tags('app') }}
    {% endblock %}

    {% block javascripts %}
      {{ encore_entry_script_tags('app') }}
    {% endblock %}
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-expand-lg navbar-blue bg-blue">
        <a class="navbar-brand" href="#"
          ><img height="50px" src="https://assets.stickpng.com/images/58428d79a6515b1e0ad75ab2.png"
        /></a>
        <button
          class="navbar-toggler"
          type="button"
          data-toggle="collapse"
          data-target="#navbarNavAltMarkup"
          aria-controls="navbarNavAltMarkup"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <a class="nav-link active" href="#"
              >Inicio <span class="sr-only">(current)</span></a
            >
            <a class="nav-link" href="{{ path('charactersList') }}">Lista de personajes</a>
            <a class="nav-link" href="{{ path('insertCharacter') }}">Crear nuevo personaje</a>            
          </div>
        </div>
      </nav>
     
      {% block contenido %} {% endblock %}
    </div>
  </body>
</html>

templates/characters/characterDetail.html.twig
{% extends 'characters/baseDisney.html.twig' %}

{% block contenido %}
<div class="container">
        <div class="row">
          <div class="col text-center">
            <h2>{{ character.nombre }}</h2>
          </div>
        </div>
        <div class="row">
          <div class="col"><img src="{{ character.imagen }}" width="400px" height="400px" style="object-fit:cover" /></div>
          <div class="col">
            <div class="row"><div class="col">{{ character.pelicula }}</div></div>
            <div class="col">
            <div class="row"><div class="col">{{ character.tipo }}</div></div>
            <div class="col">
            <div class="row"><div class="col">{{ character.localizacion }}</div></div>
          </div>
        </div>
      </div>
{% endblock %}

templates/characters/charactersList.html.twig
{% extends 'characters/baseDisney.html.twig' %}

{% block contenido %}

{% for mensaje in app.flashes('success') %}
<p>{{ mensaje }}</p>
{% endfor %}

<h2>Listado de personajes Disney</h2>
<div class="row row-cols-1 row-cols-md-2">
  {% for character in characters %}
  <div class="col mb-4">
    <div class="card" style="width: 20rem heigt: 150hg">
      <img src="{{ character.imagen }}" class="card-img-top" width="200" height="260" object-position: "center bottom;"/>
      <div class="card-body">
        <h5 class="card-title">{{ character.nombre }}</h5>
        <p class="card-text">{{ character.tipo }}</p>
        <a href="{{ path('characterDetail',{id:character.id}) }}" class="btn btn-primary">Más Info</a>
        <a href="{{ path('deleteCharacter',{id:character.id}) }}" class="btn btn-primary">Eliminar</a>
      </div>
    </div>
  </div>
  {% endfor %}
</div>

{% endblock %}

templates/characters/createCharacter.html.twig
{% extends 'characters/baseDisney.html.twig' %}

{% block contenido %}

{{ form(createForm)}}

{% endblock %}